/* Generated by tools/build_data.py from research/facts.json. Do not edit by hand. */
window.SX_DATA = {
 "asOf": "2026-09-29",
 "sources": {
  "S1": {
   "title": "Starship (vehicle page: Starship, Super Heavy, Raptor and RVac metrics)",
   "publisher": "SpaceX",
   "date": "2026-09",
   "url": "https://www.spacex.com/vehicles/starship/"
  },
  "S2": {
   "title": "Introducing Starship V3",
   "publisher": "SpaceX",
   "date": "2026-05-12",
   "url": "https://www.spacex.com/updates#starship-v3"
  },
  "S3": {
   "title": "Raptor 3 (sea level variant): Thrust 280tf, Specific impulse 350s, Engine mass 1525kg, Engine + vehicle-side commodities and hardware mass 1720kg",
   "publisher": "SpaceX on X",
   "date": "2024-08-03",
   "url": "https://x.com/SpaceX/status/1819772716339339664"
  },
  "S4": {
   "title": "Performance stats of previous versions (Raptor 1 and Raptor 2, sea level variants)",
   "publisher": "SpaceX on X",
   "date": "2024-08-03",
   "url": "https://x.com/SpaceX/status/1819795288116330594"
  },
  "S5": {
   "title": "Starship Flight 14 (mission page, timeline and post-flight summary)",
   "publisher": "SpaceX",
   "date": "2026-09-28",
   "url": "https://www.spacex.com/launches/starship-flight-14"
  },
  "S6": {
   "title": "Starship's Thirteenth Flight Test (mission page)",
   "publisher": "SpaceX",
   "date": "2026-07-24",
   "url": "https://www.spacex.com/launches/starship-flight-13"
  },
  "S7": {
   "title": "Starship's Twelfth Flight Test (mission page)",
   "publisher": "SpaceX",
   "date": "2026-05-22",
   "url": "https://www.spacex.com/launches/starship-flight-12"
  },
  "S8": {
   "title": "Starship to Orbit",
   "publisher": "SpaceX",
   "date": "2026-09-15",
   "url": "https://www.spacex.com/updates#orbital-starship"
  },
  "S9": {
   "title": "To the Moon and Beyond",
   "publisher": "SpaceX",
   "date": "2025-10-30",
   "url": "https://www.spacex.com/updates#moon-and-beyond"
  },
  "S10": {
   "title": "Starship vehicle page as archived 2025-03-13 (V2-era metrics: stack 123 m, booster 71 m, 3,400 t, 7,590 tf; ship 52 m, 1,500 t, 1,500 tf; Raptor 3.1 m tall; RVac 4.6 m tall)",
   "publisher": "SpaceX (Internet Archive copy)",
   "date": "2025-03-13",
   "url": "https://web.archive.org/web/20250313155205/https://www.spacex.com/vehicles/starship/"
  },
  "S11": {
   "title": "Starship mission pages, Flights 1 to 11, and launches list (return site 'Mechazilla' for Flights 5, 7, 8)",
   "publisher": "SpaceX",
   "date": "2023-04 to 2025-10",
   "url": "https://www.spacex.com/launches/"
  },
  "S12": {
   "title": "Raptor V3 just achieved 350 bar chamber pressure (269 tons of thrust)",
   "publisher": "Elon Musk on X",
   "date": "2023-05-13",
   "url": "https://x.com/elonmusk/status/1657249739925258240"
  },
  "S13": {
   "title": "Sea level Raptor's vacuum Isp is ~350 sec, but ~380 sec with larger vacuum-optimized nozzle",
   "publisher": "Elon Musk on X",
   "date": "2019-09-09",
   "url": "https://x.com/elonmusk/status/1171118891671490560"
  },
  "S14": {
   "title": "Stretch goal for Starship V4 is 300 tons of thrust per engine with 33 engines",
   "publisher": "Elon Musk on X",
   "date": "2026-01-23",
   "url": "https://x.com/elonmusk/status/2014749076672184631"
  },
  "S15": {
   "title": "Max demonstrated Raptor thrust is ~225 tons and min is ~90 tons",
   "publisher": "Elon Musk on X",
   "date": "2020-08-18",
   "url": "https://x.com/elonmusk/status/1295553672454311941"
  },
  "S16": {
   "title": "When Raptor reaches 300 tons of thrust at liftoff, which Raptor 3.x can probably do (certainly Raptor 4 will)",
   "publisher": "Elon Musk on X",
   "date": "2024-12-31",
   "url": "https://x.com/elonmusk/status/1873986963407344069"
  },
  "S17": {
   "title": "Starship + Super Heavy propellant mass is 4800 tons (78% O2 and 22% CH4)",
   "publisher": "Elon Musk on X",
   "date": "2020-05-08",
   "url": "https://twitter.com/elonmusk/status/1258580078218412033"
  },
  "S18": {
   "title": "Exhaust Plume Calculations for SpaceX Raptor Booster Engine (Starship PEA Appendix G)",
   "publisher": "Sierra Engineering and Software for SpaceX / FAA",
   "date": "2019-06-18",
   "url": "https://web.archive.org/web/20211020054702/https://www.faa.gov/space/stakeholder_engagement/spacex_starship/media/Appendix_G_Exhaust_Plume_Calculations.pdf"
  },
  "S19": {
   "title": "Executive Summary of the Final Tiered EA for Starship/Super Heavy Increased Cadence at Boca Chica (Table ES.2 Launch Vehicle Specifications)",
   "publisher": "FAA",
   "date": "2025-04",
   "url": "https://www.faa.gov/media/94341"
  },
  "S20": {
   "title": "Raptor presentation slide (Raptor 1: 185/200 tf; Raptor 2: 230/258 tf; Raptor 3 target: 280/306 tf), in 'Elon Musk just gave another Mars speech; this time the vision seems tangible'",
   "publisher": "SpaceX slide via Ars Technica",
   "date": "2024-04-08",
   "url": "https://arstechnica.com/space/2024/04/elon-musk-just-gave-another-mars-speech-this-time-the-vision-seems-tangible/"
  },
  "S21": {
   "title": "Flight 5 and 6 Preparations Underway as SpaceX reveals Raptor 3",
   "publisher": "NASASpaceflight",
   "date": "2024-08-09",
   "url": "https://www.nasaspaceflight.com/2024/08/flight-5-6-preparations-raptor-3/"
  },
  "S22": {
   "title": "Starship Flight 12: Block 3 Impresses on First Flight",
   "publisher": "NASASpaceflight",
   "date": "2026-05-22",
   "url": "https://www.nasaspaceflight.com/2026/05/starship-flight-12-block-3-pad-2/"
  },
  "S23": {
   "title": "Super Heavy Block 3 the Booster of the Future",
   "publisher": "NASASpaceflight",
   "date": "2026-05-18",
   "url": "https://www.nasaspaceflight.com/2026/05/super-heavy-block-3-booster-future/"
  },
  "S24": {
   "title": "Flight 12 readies for the debut of SpaceX's next Ship evolution",
   "publisher": "NASASpaceflight",
   "date": "2026-05-15",
   "url": "https://www.nasaspaceflight.com/2026/05/fligth12-debut-spacex-ship-evolution/"
  },
  "S25": {
   "title": "Starship Flight 13 achieves new firsts for SpaceX",
   "publisher": "NASASpaceflight",
   "date": "2026-07-24",
   "url": "https://www.nasaspaceflight.com/2026/07/starship-flight-13-flight/"
  },
  "S26": {
   "title": "Ship 40's flawless flight promotes next mission catch potential (embeds SpaceX post on the ox turbopump start aborts)",
   "publisher": "NASASpaceflight",
   "date": "2026-07-28",
   "url": "https://www.nasaspaceflight.com/2026/07/ship-40-catch-potential/"
  },
  "S27": {
   "title": "Ship 41 Makes it to Orbit, Booster 21 Nearly Perfect",
   "publisher": "NASASpaceflight",
   "date": "2026-09-28",
   "url": "https://www.nasaspaceflight.com/2026/09/starship-flight-14-orbit/"
  },
  "S28": {
   "title": "Flight 14 approaches as a near-term manifest sketches Starship's next steps",
   "publisher": "NASASpaceflight",
   "date": "2026-09-25",
   "url": "https://www.nasaspaceflight.com/2026/09/flight-14-starships-forward-path/"
  },
  "S29": {
   "title": "Starbase Pad 2: Design Advancements from Pad 1",
   "publisher": "NASASpaceflight",
   "date": "2025-08-19",
   "url": "https://www.nasaspaceflight.com/2025/08/starbase-pad-2-advancements-pad-1/"
  },
  "S30": {
   "title": "Raptor 1 vs Raptor 2: What did SpaceX change?",
   "publisher": "Everyday Astronaut",
   "date": "2022-07-14",
   "url": "https://everydayastronaut.com/spacex-raptor-engine-comparison/"
  },
  "S31": {
   "title": "Is SpaceX's Raptor engine the king of rocket engines?",
   "publisher": "Everyday Astronaut",
   "date": "2019-05-25",
   "url": "https://everydayastronaut.com/raptor-engine/"
  },
  "S32": {
   "title": "Starship Achieves Orbit for the First Time",
   "publisher": "SpacePolicyOnline",
   "date": "2026-09-28",
   "url": "https://spacepolicyonline.com/news/starship-achieves-orbit-for-the-first-time/"
  },
  "S33": {
   "title": "Orbits for the Starlink Group 31-1 sats: 262 x 275 km x 30.5 deg (CelesTrak)",
   "publisher": "Jonathan McDowell on X",
   "date": "2026-09-28",
   "url": "https://x.com/planet4589/status/2104691411748802577"
  },
  "S34": {
   "title": "SpaceX Starship Flight 14 live updates (quotes SpaceX: ~12 million pounds of liquid oxygen and liquid methane)",
   "publisher": "Space.com",
   "date": "2026-09-28",
   "url": "https://www.space.com/news/live/spacex-starship-flight-14-live-updates-sept-28-2026-starship-first-orbital-launch-attempt"
  },
  "S35": {
   "title": "FAA Closes SpaceX Starship Flight 12 Mishap Investigation",
   "publisher": "Aero-News Network (FAA statement)",
   "date": "2026-07-14",
   "url": "https://www.aero-news.net/index.cfm?do=main.textpost&id=DAB4BEFB-29DC-49DA-9D0C-697CBC87B746"
  },
  "S36": {
   "title": "Preparing Saturn V for Apollo 13 (363 ft, 7.5 million pounds of thrust)",
   "publisher": "NASA",
   "date": "2020-04-06",
   "url": "https://www.nasa.gov/image-article/preparing-saturn-v-apollo-13-march-24-1970/"
  },
  "S37": {
   "title": "Space Launch System fact sheet (Block 1: 322 ft, 8.8 million lb thrust, minimum 70 t; core 27.6 ft diameter)",
   "publisher": "NASA",
   "date": "2014-08",
   "url": "https://www.nasa.gov/sites/default/files/files/SLS-Fact-Sheet_aug2014-finalv3.pdf"
  },
  "S38": {
   "title": "Falcon 9 and Falcon Heavy vehicle pages",
   "publisher": "SpaceX",
   "date": "2026-09",
   "url": "https://www.spacex.com/vehicles/falcon-9/"
  },
  "S39": {
   "title": "N1 moon rocket",
   "publisher": "RussianSpaceWeb (Anatoly Zak)",
   "date": "2026-09",
   "url": "https://russianspaceweb.com/n1.html"
  },
  "S40": {
   "title": "Blue Origin Targets Super-Heavy Class New Glenn Variant (New Glenn 7x2: 45 t LEO; 3.85 Mlbf baseline)",
   "publisher": "Satellite Today",
   "date": "2025-11-20",
   "url": "https://www.satellitetoday.com/launch/2025/11/20/blue-origin-targets-super-heavy-class-new-glenn-variant/"
  },
  "S41": {
   "title": "Oxygen, phase change data",
   "publisher": "NIST Chemistry WebBook",
   "date": "2026-09",
   "url": "https://webbook.nist.gov/cgi/cbook.cgi?ID=C7782447"
  },
  "S42": {
   "title": "Methane, phase change data",
   "publisher": "NIST Chemistry WebBook",
   "date": "2026-09",
   "url": "https://webbook.nist.gov/cgi/cbook.cgi?ID=C74828"
  },
  "S43": {
   "title": "FAA warns SpaceX that massive Starship launch tower in Texas is unapproved (480-foot-tall integration tower)",
   "publisher": "CNBC",
   "date": "2021-07-14",
   "url": "https://www.cnbc.com/2021/07/14/faa-warns-spacex-it-has-not-approved-new-texas-launch-site-tower.html"
  },
  "S44": {
   "title": "Musk: 'Dream come true' to see fully stacked SpaceX Starship rocket (cited by Wikipedia for about 18,000 tiles; article text says 'thousands')",
   "publisher": "CNBC",
   "date": "2021-08-06",
   "url": "https://www.cnbc.com/2021/08/06/elon-musk-spacex-starship-fully-stacked-is-dream-come-true.html"
  },
  "S45": {
   "title": "We have since created our own new alloys and no longer use 301",
   "publisher": "Elon Musk on X",
   "date": "2026-08-23",
   "url": "https://x.com/elonmusk/status/2091617925669245333"
  },
  "S46": {
   "title": "We might be able to reduce to 2 grid fins and use S-turns for the third axis of control",
   "publisher": "Elon Musk on X",
   "date": "2026-09-25",
   "url": "https://x.com/elonmusk/status/2103540479266836485"
  },
  "S47": {
   "title": "Raptor 2 Full Flow Staged Combustion Cycle Estimate (community cycle model, Livingjw and HVM)",
   "publisher": "NASASpaceflight forum via Wikimedia Commons",
   "date": "2022-02-03",
   "url": "https://commons.wikimedia.org/wiki/File:Raptor_2_Full_Flow_Staged_Combustion_Cycle_Estimate.svg"
  },
  "S48": {
   "title": "SpaceX will use superalloys for Raptor engines (quotes Musk: SX 500, ~800 atmosphere hot oxygen-rich turbopump)",
   "publisher": "NextBigFuture",
   "date": "2018-06-22",
   "url": "https://www.nextbigfuture.com/2018/06/spacex-will-use-superalloys-for-raptor-engines.html"
  },
  "S49": {
   "title": "Path to Starship Flight 13 requires additional Booster 20 test (T-0 abort account)",
   "publisher": "NASASpaceflight",
   "date": "2026-07-22",
   "url": "https://www.nasaspaceflight.com/2026/07/path-flight-13-attempt-2-test/"
  },
  "S50": {
   "title": "Bigger is Better: Starship's Extended and Optimized Tanks; It's About Damn Time: Starship's Upgraded Flaps and Nosecone",
   "publisher": "Ringwatchers",
   "date": "2026-01",
   "url": "https://ringwatchers.com/article/s33-tanks"
  },
  "S51": {
   "title": "How NASA's Artemis III Lander Test Will Pave Way for Moon Landings",
   "publisher": "NASA",
   "date": "2026-07-15",
   "url": "https://www.nasa.gov/directorates/esdmd/artemis-campaign-development-division/human-landing-system-program/how-nasas-artemis-iii-lander-test-will-pave-way-for-moon-landings/"
  },
  "S52": {
   "title": "The Future of the Starship Program, Block 3 and Mars",
   "publisher": "NASASpaceflight",
   "date": "2025-05-30",
   "url": "https://www.nasaspaceflight.com/2025/05/future-starship-block-3-mars/"
  },
  "S53": {
   "title": "Starbase Tour and Interview with Elon Musk (V1 ship dry mass roughly 100 t)",
   "publisher": "Everyday Astronaut",
   "date": "2021-08-11",
   "url": "https://everydayastronaut.com/starbase-tour-and-interview-with-elon-musk/"
  },
  "S54": {
   "title": "SpaceX tests heat shields that will stop its Starship from burning up (orbital entry temp ~1,650 K)",
   "publisher": "Engadget",
   "date": "2019-03-18",
   "url": "https://www.engadget.com/2019-03-18-spacex-tests-starship-heat-shields.html"
  },
  "S55": {
   "title": "Ship 42 wraps chopsticks tests, Flight 14 moves to NET Sept. 22",
   "publisher": "NASASpaceflight",
   "date": "2026-09-14",
   "url": "https://www.nasaspaceflight.com/2026/09/ship-42-chopsticks-tests-flight-14-net/"
  },
  "S56": {
   "title": "Starship Block 3 development continues at Starbase and McGregor (354 s Raptor 3 test)",
   "publisher": "NASASpaceflight",
   "date": "2025-09-16",
   "url": "https://www.nasaspaceflight.com/2025/09/spacex-starship-block-3-engine-testing-mcgregor/"
  },
  "S57": {
   "title": "Space Exploration Technologies Corp. Form S-1 registration statement",
   "publisher": "SEC / SpaceX",
   "date": "2026-05-20",
   "url": "https://www.sec.gov/Archives/edgar/data/1181412/000162828026036936/spaceexplorationtechnologi.htm"
  },
  "S58": {
   "title": "Starship returns to Earth; rocket splashes down north of Hawaii after three-hour flight",
   "publisher": "Spaceflight Now",
   "date": "2026-09-28",
   "url": "https://spaceflightnow.com/2026/09/28/starship-returns-to-earth-rocket-splashes-down-north-of-hawaii-after-three-hour-flight/"
  }
 },
 "facts": {
  "stack.height": {
   "v": 124,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "407 ft. Sum of the more precise reported figures (72.3 m booster + 52.1 m ship) is 124.4 m. V2 stack was 123 m (S10)."
  },
  "stack.diameter": {
   "v": 9,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "29.5 ft, both stages."
  },
  "stack.liftoffMass": {
   "v": 5700,
   "unit": "t",
   "conf": "estimate",
   "src": [
    "S1",
    "S22"
   ],
   "note": "Not published. Estimate: 5,250 t propellant (official) plus roughly 250 to 300 t booster dry, 100 to 160 t ship dry and payload; range about 5,600 to 5,800 t. Consistent with NSF's liftoff thrust-to-weight of 'nearly 1.5'."
  },
  "stack.liftoffThrust": {
   "v": 8240,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "18.1 Mlbf. Only the 33 booster engines fire at liftoff. 33 x 250 tf = 8,250 tf; SpaceX lists 8,240 tf. The often-quoted 9,240 tf assumes 280 tf engines and is wrong for flight."
  },
  "stack.liftoffThrustkN": {
   "v": 80807,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Converted from 8,240 tf (80.8 MN)."
  },
  "stack.payloadLEOReusable": {
   "v": 100,
   "unit": "t",
   "conf": "official",
   "src": [
    "S1",
    "S57"
   ],
   "note": "'More than 100 metric tonnes to orbit in a fully reusable configuration' (displayed as 100+ t)."
  },
  "stack.payloadLEOExpendable": {
   "v": null,
   "unit": "t",
   "conf": "disputed",
   "src": [
    "S10"
   ],
   "note": "Not published for V3. SpaceX's 2025 page said 'up to 150 t fully reusable and 250 t expendable' for Starship generally; Musk's 2024 '400 t expendable' referred to the larger vehicle now called V4."
  },
  "stack.engineCount": {
   "v": 39,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "33 on Super Heavy, 6 on Starship (3 sea-level Raptor, 3 Raptor Vacuum)."
  },
  "stack.propTotal": {
   "v": 5250,
   "unit": "t",
   "conf": "official",
   "src": [
    "S1",
    "S34"
   ],
   "note": "Sum of 3,650 t (booster) and 1,600 t (ship), about 11.6 Mlb. SpaceX's Flight 14 countdown post rounded this to '~12 million pounds'."
  },
  "stack.heightV2": {
   "v": 123,
   "unit": "m",
   "conf": "official",
   "src": [
    "S10"
   ],
   "note": "403 ft, V2 ship on first-generation booster (2025)."
  },
  "booster.height": {
   "v": 72,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "236 ft. NASASpaceflight gives 72.3 m. First-generation booster was 71 m (232 ft) including the vented hot-stage ring (S10)."
  },
  "booster.diameter": {
   "v": 9,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": ""
  },
  "booster.dryMass": {
   "v": null,
   "unit": "t",
   "conf": "disputed",
   "src": [],
   "note": "Not published for any version. The widely repeated 275 t for V1/V2 has no primary source. SpaceX says V3 saves about 1 t per engine at vehicle level."
  },
  "booster.propLOX": {
   "v": 2850,
   "unit": "t",
   "conf": "estimate",
   "src": [
    "S1",
    "S17"
   ],
   "note": "Derived: 3,650 t x 78% oxygen (Musk 2020 stack split); O/F 3.6 gives 2,857 t."
  },
  "booster.propCH4": {
   "v": 800,
   "unit": "t",
   "conf": "estimate",
   "src": [
    "S1",
    "S17"
   ],
   "note": "Derived: 3,650 t x 22% methane; O/F 3.6 gives 793 t."
  },
  "booster.propTotal": {
   "v": 3650,
   "unit": "t",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "8 Mlb. First-generation booster: 3,400 t (S10)."
  },
  "booster.engineCount": {
   "v": 33,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1",
    "S2"
   ],
   "note": "All Raptor 3 on V3."
  },
  "booster.enginesCenter": {
   "v": 3,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1",
    "S23"
   ],
   "note": "On V3 the center three are clocked 108/108/144 degrees (NSF) so none fires straight at the flame-diverter ridge."
  },
  "booster.enginesInner": {
   "v": 10,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1",
    "S23"
   ],
   "note": "Inner (middle) ring. SpaceX: '13 maneuverable engines in the center' = 3 + 10."
  },
  "booster.enginesOuter": {
   "v": 20,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "'The remaining 20 around the perimeter'. Fixed (no gimbal)."
  },
  "booster.enginesGimbal": {
   "v": 13,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1",
    "S2"
   ],
   "note": "Center 3 + inner ring 10 carry thrust vector control; the outer 20 are fixed."
  },
  "booster.enginesRelight": {
   "v": 33,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S6",
    "S2"
   ],
   "note": "V3: all 33 can restart; Flight 13 flew 'the high thrust portion of the boostback burn with all 33 engines'. First-generation boosters relit only the inner 13 (outer 20 used ground spin start)."
  },
  "booster.gridFins": {
   "v": 3,
   "unit": "fins",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Reduced from four to three; each 50% larger and stronger, with catch points, re-clocked (T layout per NSF) and lowered. Shafts, actuators and fixed structure moved inside the methane tank."
  },
  "booster.material": {
   "v": "Stainless steel (SpaceX in-house alloys)",
   "unit": "",
   "conf": "official",
   "src": [
    "S45"
   ],
   "note": "Musk (2026-08-23): 'We have since created our own new alloys and no longer use 301.' Alloy name and wall thickness for V3 are not published; '30X' is a nickname."
  },
  "booster.liftoffThrust": {
   "v": 8240,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "18.1 Mlbf. First-generation booster: 7,590 tf (16.7 Mlbf) (S10)."
  },
  "booster.liftoffThrustkN": {
   "v": 80807,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Converted."
  },
  "booster.transferTube": {
   "v": "Roughly the size of a Falcon 9 first stage",
   "unit": "",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Lets all 33 engines start at once and enables faster, more reliable flips."
  },
  "booster.transferTubeLength": {
   "v": 50,
   "unit": "m",
   "conf": "reported",
   "src": [
    "S23"
   ],
   "note": "NSF: about 50 m tall and 3 m wide."
  },
  "booster.transferTubeDiameter": {
   "v": 3,
   "unit": "m",
   "conf": "reported",
   "src": [
    "S23"
   ],
   "note": ""
  },
  "booster.quickDisconnects": {
   "v": 2,
   "unit": "QDs",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Separate LOX and methane fill connections (was one)."
  },
  "booster.hotStage": {
   "v": "Integrated (not jettisoned)",
   "unit": "",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Replaces the single-use vented ring. The forward dome takes the ship's exhaust, protected by tank pressure and a non-structural steel layer; interstage actuators retract after separation. NSF describes an N1-style open truss."
  },
  "booster.shrouds": {
   "v": "Deleted",
   "unit": "",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Individual engine shrouds, the aft cavity and the CO2 fire-suppression system were removed; shielding remains between engines and around TVC hardware on the inner 13."
  },
  "booster.landingTank": {
   "v": "Separate LOX landing tank feeding all 13 inner engines",
   "unit": "",
   "conf": "reported",
   "src": [
    "S23"
   ],
   "note": "Size and exact location not published."
  },
  "booster.copvs": {
   "v": "Nearly doubled vs Block 1/2",
   "unit": "",
   "conf": "reported",
   "src": [
    "S23"
   ],
   "note": "Hold gaseous methane and oxygen for spin start and igniters, nitrogen for pneumatic valves, and landing-tank pressurant."
  },
  "booster.centerClocking": {
   "v": "108/108/144",
   "unit": "deg",
   "conf": "reported",
   "src": [
    "S23"
   ],
   "note": "An earlier NSF article gave 108/108/140, which does not sum to 360."
  },
  "booster.landingBurnSequence": {
   "v": "13, then 5, then 3 engines",
   "unit": "",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Flight 14 actual: 11 of 13 lit, then 5, then 3."
  },
  "booster.gridFinsFuture": {
   "v": "Possibly 2",
   "unit": "fins",
   "conf": "reported",
   "src": [
    "S46"
   ],
   "note": "Musk (2026-09-25): 'We might be able to reduce to 2 grid fins and use S-turns for the third axis of control.' An idea, not a plan of record."
  },
  "booster.catchesTotal": {
   "v": 3,
   "unit": "catches",
   "conf": "official",
   "src": [
    "S11"
   ],
   "note": "Flights 5 (B12), 7 (B14), 8 (B15), all first-generation boosters. No V3 booster caught as of 2026-09-29."
  },
  "ship.height": {
   "v": 52,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1",
    "S51"
   ],
   "note": "171 ft (52.1 m per NASA). External dimensions unchanged from V2; V1 was about 50.3 m (reported)."
  },
  "ship.diameter": {
   "v": 9,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": ""
  },
  "ship.dryMass": {
   "v": null,
   "unit": "t",
   "conf": "disputed",
   "src": [
    "S53",
    "S27"
   ],
   "note": "Not published for V2 or V3. Musk put V1 at roughly 100 t (2021); NSF loosely calls Ship 41 a '160-metric-ton vehicle'."
  },
  "ship.propLOX": {
   "v": 1250,
   "unit": "t",
   "conf": "estimate",
   "src": [
    "S1"
   ],
   "note": "Derived: 1,600 t x 3.6/4.6 = 1,252 t (O/F not published for Raptor 3)."
  },
  "ship.propCH4": {
   "v": 350,
   "unit": "t",
   "conf": "estimate",
   "src": [
    "S1"
   ],
   "note": "Derived: 1,600 t / 4.6 = 348 t."
  },
  "ship.propTotal": {
   "v": 1600,
   "unit": "t",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "3.5 Mlb. V2: 1,500 t (S10). V3 lowered the common and aft domes about 1.106 m (NSF) for about 100 t more."
  },
  "ship.enginesSL": {
   "v": 3,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Sea-level Raptor 3 in the center; these gimbal and do all in-space burns and landings so far."
  },
  "ship.enginesVac": {
   "v": 3,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Raptor Vacuum 3, fixed (no gimbal, reported). Tops sit slightly recessed into the LOX tank on V3 (NSF)."
  },
  "ship.enginesGimbal": {
   "v": 3,
   "unit": "engines",
   "conf": "reported",
   "src": [
    "S30"
   ],
   "note": "Only the three sea-level engines gimbal."
  },
  "ship.thrustVac": {
   "v": 1614,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "3.5 Mlbf total, in vacuum. V2: 1,500 tf (S10)."
  },
  "ship.thrustVackN": {
   "v": 15828,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Converted."
  },
  "ship.tileCount": {
   "v": 18000,
   "unit": "tiles",
   "conf": "reported",
   "src": [
    "S44"
   ],
   "note": "V1-era figure widely repeated; Wikipedia attributes it to CNBC 2021, but that article's text says only 'thousands of the tiles'. V3 count not published."
  },
  "ship.flapCount": {
   "v": 4,
   "unit": "flaps",
   "conf": "official",
   "src": [
    "S7",
    "S2"
   ],
   "note": "Two forward, two aft. V3 aft flaps use one actuator with three motors (was two actuators per flap)."
  },
  "ship.dockingDrogues": {
   "v": 4,
   "unit": "drogues",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "On the leeward side, for ship-to-ship docking and propellant transfer."
  },
  "ship.domeLowering": {
   "v": 1.106,
   "unit": "m",
   "conf": "reported",
   "src": [
    "S24"
   ],
   "note": "Common dome and aft dome lowered, adding propellant volume without changing height."
  },
  "ship.orbitEndurance": {
   "v": 48,
   "unit": "h",
   "conf": "reported",
   "src": [
    "S24"
   ],
   "note": "Design goal for V3 avionics and batteries."
  },
  "ship.copvs": {
   "v": 32,
   "unit": "COPVs (at least)",
   "conf": "reported",
   "src": [
    "S24"
   ],
   "note": "Counted on Ship 39 from raceway outlet lines."
  },
  "ship.headerTanks": {
   "v": "2 (LOX header at the nose tip, methane header sphere below it)",
   "unit": "",
   "conf": "reported",
   "src": [
    "S50",
    "S24"
   ],
   "note": "Capacities not published. V3 header feed system is 100% vacuum jacketed (official, S2)."
  },
  "ship.sensors": {
   "v": 500,
   "unit": "sensors (more than)",
   "conf": "official",
   "src": [
    "S8"
   ],
   "note": "More than 500 physical sensors."
  },
  "ship.tileTestTemp": {
   "v": 1650,
   "unit": "K",
   "conf": "reported",
   "src": [
    "S54"
   ],
   "note": "2019 tile test at Musk's stated orbital entry temperature; V3 peak heating not published."
  },
  "vehicle.avionicsUnits": {
   "v": 60,
   "unit": "units (approx.)",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Across ship and booster, integrating batteries, inverters and high-voltage distribution."
  },
  "vehicle.peakPower": {
   "v": 9,
   "unit": "MW",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Approximately 9 MW peak across both vehicles."
  },
  "vehicle.starlinkBandwidth": {
   "v": 480,
   "unit": "Mbps",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Redundant Starlink connectivity."
  },
  "vehicle.cameraViews": {
   "v": 50,
   "unit": "views (approx.)",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": ""
  },
  "raptor.cycle": {
   "v": "Full-flow staged combustion, methane and liquid oxygen",
   "unit": "",
   "conf": "reported",
   "src": [
    "S31",
    "S1"
   ],
   "note": "SpaceX's page says 'reusable methane-oxygen staged-combustion engine'. First full-flow engine to fly."
  },
  "raptor.r1.thrustSL": {
   "v": 185,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "1,814 kN."
  },
  "raptor.r1.thrustSLkN": {
   "v": 1814,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Converted."
  },
  "raptor.r1.ispSL": {
   "v": 330,
   "unit": "s",
   "conf": "reported",
   "src": [
    "S30"
   ],
   "note": "SpaceX lists 'Specific impulse: 350s' for Raptor 1 without saying sea level or vacuum; 350 s is best read as the vacuum Isp of the sea-level engine."
  },
  "raptor.r1.ispListed": {
   "v": 350,
   "unit": "s",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Condition not stated by SpaceX."
  },
  "raptor.r1.mass": {
   "v": 2080,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": ""
  },
  "raptor.r1.massWithCommodities": {
   "v": 3630,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Engine plus vehicle-side commodities and hardware."
  },
  "raptor.r1.chamberPressure": {
   "v": 250,
   "unit": "bar",
   "conf": "reported",
   "src": [
    "S30",
    "S18"
   ],
   "note": "Design goal of the first version; the 2019 FAA-filed model used 3,669.5 psia (253 bar)."
  },
  "raptor.r1.twr": {
   "v": 89,
   "unit": "ratio",
   "conf": "estimate",
   "src": [
    "S4"
   ],
   "note": "185 / 2.080."
  },
  "raptor.r1.ofRatio": {
   "v": 3.6,
   "unit": "O/F by mass",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "'Somewhat fuel-rich', 2019 booster Raptor."
  },
  "raptor.r1.expansionRatio": {
   "v": 34.34,
   "unit": ":1",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "'Regeneratively-cooled thrust chamber nozzle', 2019 booster Raptor."
  },
  "raptor.r1.exitDiameter": {
   "v": 1.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "51.226 in."
  },
  "raptor.r1.throatDiameter": {
   "v": 0.222,
   "unit": "m",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "Throat radius 4.362 in. Raptor 2 later 'opened the throat' for more thrust (S30)."
  },
  "raptor.r1.filmCooling": {
   "v": 1.2,
   "unit": "% of flow",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "Fuel-rich gas through three slots in the converging section (2019 model). SpaceX was reported in 2022 to be working to remove throat film cooling (S30)."
  },
  "raptor.r1.cStarEfficiency": {
   "v": 98.6,
   "unit": "%",
   "conf": "official",
   "src": [
    "S18"
   ],
   "note": "2019 FAA-filed model."
  },
  "raptor.r1.throttleMin": {
   "v": 40,
   "unit": "% of max",
   "conf": "official",
   "src": [
    "S15"
   ],
   "note": "Musk 2020: max demonstrated ~225 t, min ~90 t; limited by preburner flameout."
  },
  "raptor.rvac1.thrust": {
   "v": 200,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S20"
   ],
   "note": "SpaceX presentation slide, April 2024."
  },
  "raptor.r2.thrustSL": {
   "v": 230,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S4",
    "S2"
   ],
   "note": "507,000 lbf."
  },
  "raptor.r2.thrustSLkN": {
   "v": 2256,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Converted."
  },
  "raptor.r2.ispSL": {
   "v": 327,
   "unit": "s",
   "conf": "reported",
   "src": [
    "S30"
   ],
   "note": "SpaceX lists 347 s without a condition (best read as vacuum Isp of the sea-level engine)."
  },
  "raptor.r2.ispListed": {
   "v": 347,
   "unit": "s",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Condition not stated by SpaceX."
  },
  "raptor.r2.mass": {
   "v": 1630,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S4",
    "S2"
   ],
   "note": ""
  },
  "raptor.r2.massWithCommodities": {
   "v": 2875,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S4"
   ],
   "note": "Engine plus vehicle-side commodities and hardware."
  },
  "raptor.r2.chamberPressure": {
   "v": 300,
   "unit": "bar",
   "conf": "reported",
   "src": [
    "S30"
   ],
   "note": "'Up 50 bar from Raptor 1'."
  },
  "raptor.r2.twr": {
   "v": 141,
   "unit": "ratio",
   "conf": "estimate",
   "src": [
    "S4"
   ],
   "note": "230 / 1.630."
  },
  "raptor.r2.height": {
   "v": 3.1,
   "unit": "m",
   "conf": "official",
   "src": [
    "S10"
   ],
   "note": "SpaceX page, 2025 (10.2 ft). Same figure appeared for the 2019 engine."
  },
  "raptor.r2.diameter": {
   "v": 1.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S10"
   ],
   "note": ""
  },
  "raptor.r2.gimbalRange": {
   "v": 15,
   "unit": "deg",
   "conf": "reported",
   "src": [
    "S30"
   ],
   "note": ""
  },
  "raptor.rvac2.thrust": {
   "v": 258,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S2",
    "S20"
   ],
   "note": "568,000 lbf."
  },
  "raptor.rvac2.height": {
   "v": 4.6,
   "unit": "m",
   "conf": "official",
   "src": [
    "S10"
   ],
   "note": "15.1 ft."
  },
  "raptor.rvac2.diameter": {
   "v": 2.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S10"
   ],
   "note": ""
  },
  "raptor.r3.thrustSL": {
   "v": 250,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S2",
    "S1"
   ],
   "note": "Flight rating on Starship V3: 551,000 lbf. 280 tf was the August 2024 ground-test spec and remains the stated goal (NSF)."
  },
  "raptor.r3.thrustSLkN": {
   "v": 2452,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Converted from 250 tf."
  },
  "raptor.r3.thrustSLDemonstrated": {
   "v": 280,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S3"
   ],
   "note": "2,746 kN. Spec published at the August 2024 reveal; not the V3 flight rating."
  },
  "raptor.r3.thrustVacOfSLEngine": {
   "v": 263,
   "unit": "tf",
   "conf": "estimate",
   "src": [
    "S1"
   ],
   "note": "Derived from SpaceX's ship total: (1,614 - 3 x 275) / 3. The 13 tf gain over sea level implies an exit area of about 1.26 m2, consistent with the 1.3 m diameter."
  },
  "raptor.r3.ispSL": {
   "v": 333,
   "unit": "s",
   "conf": "estimate",
   "src": [
    "S1",
    "S3"
   ],
   "note": "Not published. Derived: 350 s x 250 / 263 = about 333 s (range about 330 to 335). Raptor 2 was about 327 s."
  },
  "raptor.r3.ispVac": {
   "v": 350,
   "unit": "s",
   "conf": "disputed",
   "src": [
    "S3",
    "S13"
   ],
   "note": "SpaceX lists 'Specific impulse: 350s' for the sea-level Raptor 3 without a condition; Musk (2019) said the sea-level Raptor's vacuum Isp is ~350 s. Read as vacuum Isp of the sea-level engine."
  },
  "raptor.r3.mass": {
   "v": 1525,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S3",
    "S2"
   ],
   "note": "Down from 1,630 kg (Raptor 2)."
  },
  "raptor.r3.massWithCommodities": {
   "v": 1720,
   "unit": "kg",
   "conf": "official",
   "src": [
    "S3"
   ],
   "note": "Engine plus vehicle-side commodities and hardware (Raptor 2: 2,875 kg)."
  },
  "raptor.r3.vehicleSideMass": {
   "v": 195,
   "unit": "kg",
   "conf": "estimate",
   "src": [
    "S3",
    "S4"
   ],
   "note": "1,720 - 1,525. Raptor 2: 1,245 kg; Raptor 1: 1,550 kg."
  },
  "raptor.r3.massSavingPerEngine": {
   "v": 1,
   "unit": "t",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "'Approximately 1 ton per engine' at vehicle level. Derived from the published masses: 2,875 - 1,720 = 1,155 kg."
  },
  "raptor.r3.chamberPressure": {
   "v": 350,
   "unit": "bar",
   "conf": "official",
   "src": [
    "S12"
   ],
   "note": "Demonstrated in test by a 'Raptor V3' development engine in May 2023 at 269 tf. The flight-rating chamber pressure at 250 tf is not published; about 325 to 330 bar is an estimate. The 330 bar often cited traces to a 2022 'Raptor 2.5' target (250 tf, 330 bar, S30), not a Raptor 3 spec."
  },
  "raptor.r3.ofRatio": {
   "v": 3.6,
   "unit": "O/F by mass",
   "conf": "estimate",
   "src": [
    "S18",
    "S17"
   ],
   "note": "Not published for Raptor 3. 3.60 is the official 2019 value; Musk's 2020 stack split (78% O2) implies about 3.55."
  },
  "raptor.r3.throttleMin": {
   "v": null,
   "unit": "% of max",
   "conf": "estimate",
   "src": [
    "S15",
    "S9"
   ],
   "note": "Not published. The 2020 engine throttled to about 40% (90 of 225 t). SpaceX demonstrated a lunar-landing throttle profile (2025)."
  },
  "raptor.r3.gimbalRange": {
   "v": 15,
   "unit": "deg",
   "conf": "estimate",
   "src": [
    "S30"
   ],
   "note": "Raptor 2 figure; Raptor 3 gimbal range not published."
  },
  "raptor.r3.expansionRatio": {
   "v": null,
   "unit": ":1",
   "conf": "estimate",
   "src": [
    "S18"
   ],
   "note": "Not published. The 2019 engine was 34.34:1; Raptor 2 opened the throat, lowering it. Roughly 30 to 34:1 is plausible for Raptor 3 (estimate)."
  },
  "raptor.r3.exitDiameter": {
   "v": 1.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "SpaceX lists engine diameter 1.3 m (4.2 ft); the nozzle exit is the widest point. 2019 engine exit: 1.30 m (S18)."
  },
  "raptor.r3.height": {
   "v": 2.9,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "9.5 ft (Raptor 2: 3.1 m)."
  },
  "raptor.r3.diameter": {
   "v": 1.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "4.2 ft."
  },
  "raptor.r3.twr": {
   "v": 164,
   "unit": "ratio",
   "conf": "estimate",
   "src": [
    "S2",
    "S3"
   ],
   "note": "250 / 1.525 = 163.9 at the flight rating; 184 at 280 tf. Including vehicle-side hardware: 145."
  },
  "raptor.r3.massFlow": {
   "v": 750,
   "unit": "kg/s",
   "conf": "estimate",
   "src": [
    "S1",
    "S3"
   ],
   "note": "Derived: 263 tf vacuum / (350 s x g0) = about 751 kg/s; at O/F 3.6 about 590 kg/s LOX and 165 kg/s methane."
  },
  "raptor.r3.firstHotfire": {
   "v": "2024-08",
   "unit": "",
   "conf": "reported",
   "src": [
    "S21"
   ],
   "note": "First public firing of Raptor 3 SN1 at McGregor, early August 2024 (Shotwell photo posted 2024-08-08). A development engine called 'Raptor V3' had already reached 350 bar in May 2023 (S12)."
  },
  "raptor.r3.firstFlight": {
   "v": "2026-05-22",
   "unit": "",
   "conf": "official",
   "src": [
    "S7"
   ],
   "note": "Flight 12 (B19/S39)."
  },
  "raptor.r3.firstInSpaceRelight": {
   "v": "2026-07-24",
   "unit": "",
   "conf": "official",
   "src": [
    "S6"
   ],
   "note": "Flight 13, Ship 40."
  },
  "raptor.r3.orbitInsertionBurn": {
   "v": 19,
   "unit": "s",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan: one sea-level Raptor, T+25:17 to T+25:36."
  },
  "raptor.r3.deorbitBurn": {
   "v": 11,
   "unit": "s",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan: one sea-level Raptor, T+8:52:37 to 8:52:48. Actual deorbit came early at about T+2:12:18 (NSF)."
  },
  "raptor.r3.runTime": {
   "v": 40000,
   "unit": "s (more than)",
   "conf": "official",
   "src": [
    "S9"
   ],
   "note": "Cumulative Raptor 3 run time as of 2025-10-30 (Raptor 2: more than 226,000 s)."
  },
  "raptor.r3.longestTest": {
   "v": 354,
   "unit": "s",
   "conf": "reported",
   "src": [
    "S56"
   ],
   "note": "September 2025; not re-verified in this pass."
  },
  "raptor.r3.heatShield": {
   "v": "None needed",
   "unit": "",
   "conf": "official",
   "src": [
    "S4",
    "S2"
   ],
   "note": "'Eliminating the need for engine heatshields.' Sensors and controllers are internally integrated and covered by engine thermal protection."
  },
  "raptor.r3.ignition": {
   "v": "Redesigned ignition system (reported: acoustic resonance igniters)",
   "unit": "",
   "conf": "reported",
   "src": [
    "S2",
    "S22"
   ],
   "note": "SpaceX confirms a 'redesigned ignition system'; NSF reports acoustic igniters with no spark or moving parts (Raptor 2 used spark torch igniters)."
  },
  "raptor.r3.spinStartGas": {
   "v": "Gaseous oxygen and gaseous methane",
   "unit": "",
   "conf": "reported",
   "src": [
    "S22",
    "S23"
   ],
   "note": "Earlier Raptors used helium or nitrogen. NSF: booster COPVs hold GOX and GCH4 for spin start and igniters. SpaceX confirms only 'a new Raptor startup method'."
  },
  "raptor.r3.flanges": {
   "v": "Flangeless high-pressure side; flanges remain on the low-pressure side",
   "unit": "",
   "conf": "reported",
   "src": [
    "S21"
   ],
   "note": "Removing flanges and seals lets the engine run at higher pressure."
  },
  "raptor.r3.otpDischarge": {
   "v": 700,
   "unit": "bar",
   "conf": "estimate",
   "src": [
    "S47",
    "S48"
   ],
   "note": "Community Raptor 2 cycle model: about 696 bar. Musk (2018) described a '~800 atmosphere, hot, oxygen-rich turbopump'."
  },
  "raptor.r3.ftpDischarge": {
   "v": 886,
   "unit": "bar",
   "conf": "estimate",
   "src": [
    "S47"
   ],
   "note": "Community Raptor 2 cycle model; the highest pressure in the engine. Not published by SpaceX."
  },
  "raptor.r3.preburnerPressure": {
   "v": 611,
   "unit": "bar",
   "conf": "estimate",
   "src": [
    "S47"
   ],
   "note": "Community Raptor 2 model, both preburners."
  },
  "raptor.r3.fuelPreburnerTemp": {
   "v": 860,
   "unit": "K",
   "conf": "estimate",
   "src": [
    "S47"
   ],
   "note": "Community Raptor 2 model."
  },
  "raptor.r3.oxPreburnerTemp": {
   "v": 760,
   "unit": "K",
   "conf": "estimate",
   "src": [
    "S47"
   ],
   "note": "Community Raptor 2 model."
  },
  "raptor.r3.chamberTemp": {
   "v": 3500,
   "unit": "K",
   "conf": "reported",
   "src": [
    "S31"
   ],
   "note": "Typical methalox combustion temperature, not a SpaceX figure."
  },
  "raptor.r3.otpPower": {
   "v": null,
   "unit": "MW",
   "conf": "disputed",
   "src": [
    "S47"
   ],
   "note": "Community model gives about 31 MW (oxygen pump) and 37 MW (fuel pump) for Raptor 2; the 31 MW figure has been questioned. Not published."
  },
  "raptor.material.sx500": {
   "v": "SX500 superalloy",
   "unit": "",
   "conf": "official",
   "src": [
    "S48"
   ],
   "note": "Musk (2018): in-house superalloy with extreme oxidation resistance for the '~800 atmosphere, hot, oxygen-rich turbopump'."
  },
  "raptor.rvac3.thrust": {
   "v": 275,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S2",
    "S1"
   ],
   "note": "606,000 lbf. The April 2024 target was 306 tf (S20)."
  },
  "raptor.rvac3.thrustkN": {
   "v": 2697,
   "unit": "kN",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Converted."
  },
  "raptor.rvac3.isp": {
   "v": 380,
   "unit": "s",
   "conf": "estimate",
   "src": [
    "S13"
   ],
   "note": "Not published for Raptor Vacuum 3. Musk's long-standing figure: ~380 s 'with larger vacuum-optimized nozzle'."
  },
  "raptor.rvac3.expansionRatio": {
   "v": null,
   "unit": ":1",
   "conf": "estimate",
   "src": [],
   "note": "Not published. Older statements range from about 80 (2021) to 200 (2016 design). If RVac 3 shares the sea-level throat, a 2.3 m exit implies roughly 90 to 100:1 (estimate)."
  },
  "raptor.rvac3.exitDiameter": {
   "v": 2.3,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "SpaceX lists RVac diameter 2.3 m (7.5 ft); the nozzle exit is the widest point."
  },
  "raptor.rvac3.height": {
   "v": 4.4,
   "unit": "m",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "14.4 ft (RVac 2: 4.6 m)."
  },
  "raptor.rvac3.thrustTarget2024": {
   "v": 306,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S20"
   ],
   "note": "Target on SpaceX's April 2024 slide, not a flight rating."
  },
  "raptor.v4.thrustGoal": {
   "v": 300,
   "unit": "tf",
   "conf": "official",
   "src": [
    "S14",
    "S16"
   ],
   "note": "Musk stretch goal for Starship V4: 300 t per engine, 33 engines, about 10,000 t total."
  },
  "raptor.program.enginesBuilt": {
   "v": 600,
   "unit": "engines",
   "conf": "official",
   "src": [
    "S9"
   ],
   "note": "'More than three dozen Starships and 600 Raptor rocket engines' produced as of 2025-10-30 (all versions)."
  },
  "raptor.program.r3EnginesFlown": {
   "v": 117,
   "unit": "engines",
   "conf": "estimate",
   "src": [
    "S5",
    "S6",
    "S7"
   ],
   "note": "3 flights x 39 engines; production totals not public."
  },
  "propellant.loxTemp": {
   "v": null,
   "unit": "K",
   "conf": "estimate",
   "src": [
    "S41"
   ],
   "note": "Not published. Subcooled LOX must sit between its freezing point (54.4 K) and boiling point (90.2 K)."
  },
  "propellant.ch4Temp": {
   "v": null,
   "unit": "K",
   "conf": "estimate",
   "src": [
    "S42"
   ],
   "note": "Not published. Subcooled methane must sit between its freezing point (90.7 K) and boiling point (111.7 K)."
  },
  "propellant.loxBoil": {
   "v": 90.19,
   "unit": "K",
   "conf": "official",
   "src": [
    "S41"
   ],
   "note": "Normal boiling point (-183 C)."
  },
  "propellant.loxFreeze": {
   "v": 54.36,
   "unit": "K",
   "conf": "official",
   "src": [
    "S41"
   ],
   "note": "Triple point."
  },
  "propellant.ch4Boil": {
   "v": 111.67,
   "unit": "K",
   "conf": "official",
   "src": [
    "S42"
   ],
   "note": "Normal boiling point (-161.5 C)."
  },
  "propellant.ch4Freeze": {
   "v": 90.69,
   "unit": "K",
   "conf": "official",
   "src": [
    "S42"
   ],
   "note": "Triple point."
  },
  "propellant.ofMass": {
   "v": 3.6,
   "unit": "O/F by mass",
   "conf": "estimate",
   "src": [
    "S18",
    "S17"
   ],
   "note": "Official 2019 engine value is 3.60; not published for Raptor 3."
  },
  "propellant.stackO2Fraction": {
   "v": 78,
   "unit": "% by mass",
   "conf": "official",
   "src": [
    "S17"
   ],
   "note": "Musk 2020: '78% O2 and 22% CH4'."
  },
  "propellant.loadTime": {
   "v": 34,
   "unit": "min",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Flight 14 countdown: booster LOX load starts T-36:33, booster load complete T-2:50."
  },
  "tower.height": {
   "v": 146,
   "unit": "m",
   "conf": "reported",
   "src": [
    "S43"
   ],
   "note": "Pad 1 tower, 480 ft per a 2021 FAA letter. Pad 2 tower height not published."
  },
  "tower.chopsticks": {
   "v": "Two catch arms on a moving carriage; on Pad 2 they are shorter and use electromechanical main actuators (hydraulic on Pad 1)",
   "unit": "",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "NSF: Pad 2 arms about 10 m shorter than Pad 1's and rated to lift 700 US tons (about 635 t), load-tested May 2025."
  },
  "tower.chopsticksLift": {
   "v": 635,
   "unit": "t",
   "conf": "reported",
   "src": [
    "S29"
   ],
   "note": "700 US tons."
  },
  "ground.holdDownClamps": {
   "v": 20,
   "unit": "clamps",
   "conf": "reported",
   "src": [
    "S29"
   ],
   "note": "New design on Pad 2."
  },
  "ground.boosterQDs": {
   "v": 2,
   "unit": "QDs",
   "conf": "official",
   "src": [
    "S2"
   ],
   "note": "Split methane and oxygen mechanisms on the opposite side of the mount; Pad 2 has no outer-engine spin-start QDs."
  },
  "ground.delugeWater": {
   "v": 422000,
   "unit": "US gal (max per operation)",
   "conf": "official",
   "src": [
    "S29"
   ],
   "note": "FAA environmental assessment figure as quoted by NSF (about 1,600 m3)."
  },
  "ground.flameDiverterActivation": {
   "v": -17,
   "unit": "s",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "T-17 s; booster engine startup command at T-3 s."
  },
  "flight.integratedFlights": {
   "v": 14,
   "unit": "flights",
   "conf": "official",
   "src": [
    "S11",
    "S5"
   ],
   "note": "13 suborbital, 1 orbital, through 2026-09-29."
  },
  "flight.firstOrbit": {
   "v": "2026-09-28",
   "unit": "",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Flight 14, B21/S41."
  },
  "flight.f14Orbit": {
   "v": "262 x 275 km",
   "unit": "",
   "conf": "disputed",
   "src": [
    "S33",
    "S27"
   ],
   "note": "McDowell (CelesTrak data for the deployed Starlinks): 262 x 275 km at 30.5 deg. NSF: 262 x 277 km at 32 deg (32 deg was the planned inclination)."
  },
  "flight.f14Starlinks": {
   "v": 26,
   "unit": "satellites",
   "conf": "official",
   "src": [
    "S5"
   ],
   "note": "Starlink V3, first operational payload delivered to orbit by Starship."
  },
  "flight.f14Splashdown": {
   "v": 11307,
   "unit": "s after liftoff",
   "conf": "reported",
   "src": [
    "S32",
    "S27",
    "S58"
   ],
   "note": "T+3:08:27 (SpacePolicyOnline); NSF gives T+3:08:30. North Pacific, north of Hawaii, after an early deorbit."
  },
  "flight.f13Abort": {
   "v": "4 of 33 engines failed to start at T-0 (2026-07-16)",
   "unit": "",
   "conf": "official",
   "src": [
    "S26",
    "S49"
   ],
   "note": "SpaceX: 'Four of Super Heavy's 33 Raptor engines aborted at startup due to issues with their ox turbopumps.' NSF: six engines showed low LOX turbopump pressure from moisture and all six were replaced; Musk had said two. First full-stack ignition abort."
  },
  "flight.shipCatchRehearsal": {
   "v": "Ship 42 lifted by the Pad 2 chopsticks, September 2026",
   "unit": "",
   "conf": "reported",
   "src": [
    "S55"
   ],
   "note": "Fit checks and a QD-arm reconnection rehearsal ahead of a possible first ship catch."
  },
  "flight.shipCatches": {
   "v": 0,
   "unit": "catches",
   "conf": "official",
   "src": [
    "S8"
   ],
   "note": "No ship has been caught as of 2026-09-29."
  },
  "flight.orbitalSpeedLEO": {
   "v": 28000,
   "unit": "km/h",
   "conf": "official",
   "src": [
    "S8"
   ],
   "note": "SpaceX: about 17,500 mph in low Earth orbit. Circular speed at 275 km is 7.74 km/s (27,880 km/h, derived)."
  },
  "flight.next": {
   "v": "Flight 15 NET 2026-10-19; first LC-39A launch NET 2026-10-30",
   "unit": "",
   "conf": "reported",
   "src": [
    "S28"
   ],
   "note": "From provisional CADENA air-traffic slides; likely to slip. LC-39A not yet licensed for Starship."
  },
  "faa.envelope.booster": {
   "v": "80 m, 35 engines, 103 MN, 4,100 t propellant",
   "unit": "",
   "conf": "official",
   "src": [
    "S19"
   ],
   "note": "'Upgraded Super Heavy' analyzed by the FAA (future V4-class), not the current vehicle."
  },
  "faa.envelope.ship": {
   "v": "70 m, 9 engines, 28.7 MN, 2,650 t propellant",
   "unit": "",
   "conf": "official",
   "src": [
    "S19"
   ],
   "note": "'Upgraded Starship' analyzed by the FAA (future)."
  },
  "v4.stackHeight": {
   "v": 142,
   "unit": "m",
   "conf": "reported",
   "src": [
    "S52"
   ],
   "note": "Goal from Musk's May 2025 talk as reported by NSF."
  },
  "v4.shipEngines": {
   "v": 9,
   "unit": "engines",
   "conf": "reported",
   "src": [
    "S52"
   ],
   "note": "3 sea-level + 6 RVac (goal)."
  },
  "v4.payloadReusable": {
   "v": 200,
   "unit": "t",
   "conf": "reported",
   "src": [
    "S57"
   ],
   "note": "S-1: payload 'could reach 200 metric tons, potentially as soon as Starship V4' (as read in dossier 04; forward-looking)."
  },
  "mars.cargoOffer": {
   "v": "NET 2028 at $100 million per metric ton",
   "unit": "",
   "conf": "official",
   "src": [
    "S1"
   ],
   "note": "Text on SpaceX's current Starship page."
  }
 },
 "timeline": [
  {
   "t": 0,
   "id": "liftoff",
   "label": "Liftoff: all 33 Raptor 3 engines running",
   "speed_kmh": 0,
   "alt_km": 0,
   "who": "both",
   "src": [
    "S5"
   ],
   "note": "Flight 14, 2026-09-28 12:48:59 UTC. Booster engine start command at T-3 s; one booster engine (a center engine, per NSF) later shut down on ascent."
  },
  {
   "t": 58,
   "id": "maxq",
   "label": "Max Q: peak aerodynamic stress",
   "speed_kmh": null,
   "alt_km": null,
   "who": "both",
   "src": [
    "S5"
   ],
   "note": "Flight 14 and 13 plan: T+0:58; Flight 12: T+0:45. Speed and altitude not published for V3."
  },
  {
   "t": 140,
   "id": "meco",
   "label": "Super Heavy MECO (most engines cut off)",
   "speed_kmh": null,
   "alt_km": null,
   "who": "booster",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+2:20 (Flight 13: T+2:18). How many V3 engines stay lit is not published; V1/V2 kept the 3 center engines running."
  },
  {
   "t": 142,
   "id": "hotstage",
   "label": "Hot staging: ship's six Raptors ignite, stages separate",
   "speed_kmh": null,
   "alt_km": null,
   "who": "both",
   "src": [
    "S5",
    "S2"
   ],
   "note": "Flight 14 plan T+2:22. V3 integrated hot stage: the ship's exhaust hits the booster's protected forward dome."
  },
  {
   "t": 147,
   "id": "boostback",
   "label": "Flip and boostback burn start",
   "speed_kmh": null,
   "alt_km": null,
   "who": "booster",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+2:27. Actual: 31 of 33 planned engines relit; the burn intentionally used up the main-tank LOX."
  },
  {
   "t": 187,
   "id": "boostbackEnd",
   "label": "Boostback burn shutdown",
   "speed_kmh": null,
   "alt_km": null,
   "who": "booster",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+3:07."
  },
  {
   "t": 396,
   "id": "boosterLandingBurn",
   "label": "Booster landing burn: 13 engines, then 5, then 3",
   "speed_kmh": null,
   "alt_km": null,
   "who": "booster",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+6:36. Actual: 11 of 13 lit, then 5, then 3."
  },
  {
   "t": 421,
   "id": "boosterCatch",
   "label": "Booster landing burn ends: soft splashdown in the Gulf (tower catch on future flights)",
   "speed_kmh": 0,
   "alt_km": 0,
   "who": "booster",
   "src": [
    "S5",
    "S11"
   ],
   "note": "Flight 14 plan T+7:01; the booster splashed down and its flight termination system was then fired as a demonstration. No V3 booster has been caught; first-generation boosters were caught on Flights 5, 7 and 8."
  },
  {
   "t": 491,
   "id": "seco",
   "label": "Starship engine cutoff (SECO) on a passively safe suborbital path",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5",
    "S8"
   ],
   "note": "Flight 14 plan T+8:11. One RVac shut down early; the other five engines burned longer. Speed and altitude not published."
  },
  {
   "t": 1517,
   "id": "relight",
   "label": "Orbit insertion: one sea-level Raptor 3 relights for about 19 s",
   "speed_kmh": 28000,
   "alt_km": 270,
   "who": "ship",
   "src": [
    "S5",
    "S8",
    "S33"
   ],
   "note": "Flight 14 plan T+25:17 to T+25:36; first orbit. Speed and altitude are post-burn approximations: orbit 262 x 275 km (McDowell), LEO speed about 17,500 mph (SpaceX)."
  },
  {
   "t": 2047,
   "id": "deploy",
   "label": "Payload deploy start: 26 Starlink V3 satellites through the PEZ door",
   "speed_kmh": 28000,
   "alt_km": 270,
   "who": "ship",
   "src": [
    "S5",
    "S33"
   ],
   "note": "Flight 14 plan T+34:07; deploy complete T+1:04:39."
  },
  {
   "t": 3879,
   "id": "deployEnd",
   "label": "Payload deploy complete",
   "speed_kmh": 28000,
   "alt_km": 270,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+1:04:39."
  },
  {
   "t": 31957,
   "id": "deorbit",
   "label": "Deorbit burn: one sea-level Raptor 3 for about 11 s",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5",
    "S27"
   ],
   "note": "Flight 14 plan T+8:52:37 (full-length mission). Actual: early deorbit at about T+2:12:18 after a conservative decision following the RVac engine-out."
  },
  {
   "t": 34136,
   "id": "entry",
   "label": "Atmospheric entry, belly first",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+9:28:56. Entry interface speed and altitude not published."
  },
  {
   "t": 34556,
   "id": "peakHeat",
   "label": "Peak heating (approximate)",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Estimate only: SpaceX does not publish the time. It falls between entry (T+9:28:56) and transonic (T+9:47:29); shown about 7 minutes after entry."
  },
  {
   "t": 35249,
   "id": "transonic",
   "label": "Starship is transonic",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+9:47:29; subsonic at T+9:48:07."
  },
  {
   "t": 35411,
   "id": "landingBurn",
   "label": "Landing burn start: three sea-level Raptors relight",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+9:50:11. Steps from 3 to 2 engines at T+9:50:21 and 2 to 1 at T+9:50:28."
  },
  {
   "t": 35413,
   "id": "flip",
   "label": "Landing flip from belly-first to vertical",
   "speed_kmh": null,
   "alt_km": null,
   "who": "ship",
   "src": [
    "S5"
   ],
   "note": "Flight 14 plan T+9:50:13, two seconds after landing burn start."
  },
  {
   "t": 35430,
   "id": "splashdown",
   "label": "Splashdown (tower catch on future flights)",
   "speed_kmh": 0,
   "alt_km": 0,
   "who": "ship",
   "src": [
    "S5",
    "S32"
   ],
   "note": "Flight 14 plan T+9:50:30 off Chile. Actual Flight 14 splashdown: T+3:08:27 (11,307 s) north of Hawaii, all three sea-level engines relit for the flip and burn."
  }
 ],
 "flights": [
  {
   "n": 1,
   "date": "2023-04-20",
   "booster": "B7",
   "ship": "S24",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "Multiple engines out, stages never separated; vehicle tumbled and was destroyed; apogee about 39 km; pad foundation damaged.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 2,
   "date": "2023-11-18",
   "booster": "B9",
   "ship": "S25",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "First hot staging; booster broke up at about 90 km during boostback; ship reached about 150 km and 24,000 km/h before loss near the end of its burn.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 3,
   "date": "2024-03-14",
   "booster": "B10",
   "ship": "S28",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "Ship completed its ascent burn, opened the payload door and moved about 5 t of LOX between tanks; lost on entry; booster lost at about 462 m during its landing burn.",
   "src": [
    "S11",
    "S9"
   ]
  },
  {
   "n": 4,
   "date": "2024-06-06",
   "booster": "B11",
   "ship": "S29",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "First soft splashdowns of both stages: booster at 7 min 24 s in the Gulf, ship in the Indian Ocean at 1 h 06 min despite flap damage.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 5,
   "date": "2024-10-13",
   "booster": "B12",
   "ship": "S30",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "First booster catch by the tower chopsticks; ship splashed down on target at 1:05:40.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 6,
   "date": "2024-11-19",
   "booster": "B13",
   "ship": "S31",
   "version": "V1",
   "pad": "Pad 1",
   "outcome": "Tower health checks aborted the catch and the booster diverted to a soft splashdown; ship made the first in-space Raptor relight and splashed down.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 7,
   "date": "2025-01-16",
   "booster": "B14",
   "ship": "S33",
   "version": "V2 ship, first-generation booster",
   "pad": "Pad 1",
   "outcome": "Second booster catch; first V2 ship lost about 8.5 min in after a fire in its aft section.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 8,
   "date": "2025-03-06",
   "booster": "B15",
   "ship": "S34",
   "version": "V2 ship, first-generation booster",
   "pad": "Pad 1",
   "outcome": "Third booster catch; ship lost about 9.5 min in after an energetic event in the aft section took out several engines.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 9,
   "date": "2025-05-27",
   "booster": "B14-2",
   "ship": "S35",
   "version": "V2 ship, first-generation booster",
   "pad": "Pad 1",
   "outcome": "First reflown booster, lost at landing burn start after a high angle-of-attack test; ship reached space but the payload door stuck and it was lost about 46 min in.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 10,
   "date": "2025-08-26",
   "booster": "B16",
   "ship": "S37",
   "version": "V2 ship, first-generation booster",
   "pad": "Pad 1",
   "outcome": "All major objectives met: booster engine-out landing test and splashdown; ship deployed 8 Starlink simulators, relit a Raptor and splashed down on target.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 11,
   "date": "2025-10-13",
   "booster": "B15-2",
   "ship": "S38",
   "version": "V2 ship, first-generation booster",
   "pad": "Pad 1",
   "outcome": "Reflown booster flew the V3-style landing burn and splashed down; ship deployed 8 simulators, relit a Raptor and splashed down; last V2 and last Pad 1 flight.",
   "src": [
    "S11"
   ]
  },
  {
   "n": 12,
   "date": "2026-05-22",
   "booster": "B19",
   "ship": "S39",
   "version": "V3",
   "pad": "Pad 2",
   "outcome": "First V3 and Raptor 3 flight: booster lost one engine, flipped the wrong way, managed only a partial boostback and hit the Gulf hard; ship lost one RVac but reached its trajectory, deployed 22 satellites, skipped its relight and splashed down on two engines.",
   "src": [
    "S7",
    "S22",
    "S35"
   ]
  },
  {
   "n": 13,
   "date": "2026-07-24",
   "booster": "B20",
   "ship": "S40",
   "version": "V3",
   "pad": "Pad 2",
   "outcome": "First 33-engine boostback (ended early); too few engines lit for landing and the booster hit the Gulf hard; ship deployed 20 Starlink V3, made the first Raptor 3 in-space relight and floated intact after splashdown.",
   "src": [
    "S6",
    "S25",
    "S26"
   ]
  },
  {
   "n": 14,
   "date": "2026-09-28",
   "booster": "B21",
   "ship": "S41",
   "version": "V3",
   "pad": "Pad 2",
   "outcome": "First orbital flight: booster lost one engine, relit 31 of 33 for boostback and 11 of 13 for landing, soft Gulf splashdown; ship lost one RVac, reached orbit with a single-engine burn, deployed 26 Starlink V3, deorbited early and splashed down north of Hawaii at T+3:08:27.",
   "src": [
    "S5",
    "S27",
    "S32"
   ]
  }
 ],
 "comparisons": [
  {
   "name": "Saturn V",
   "height_m": 110.6,
   "diameter_m": 10.1,
   "thrust_MN": 33.4,
   "payload_leo_t": 140,
   "src": [
    "S36"
   ],
   "note": "363 ft; 7.5 million lbf. Diameter reported (33 ft). LEO payload disputed: about 118 t (payload only) to 140 t (including S-IVB and residuals)."
  },
  {
   "name": "SLS Block 1",
   "height_m": 98.1,
   "diameter_m": 8.4,
   "thrust_MN": 39.1,
   "payload_leo_t": 70,
   "src": [
    "S37"
   ],
   "note": "322 ft; 8.8 million lbf; core stage 27.6 ft wide. NASA fact sheet gives a 70 t minimum; later charts show about 95 t."
  },
  {
   "name": "N1",
   "height_m": 105,
   "diameter_m": 17,
   "thrust_MN": 44.1,
   "payload_leo_t": 95,
   "src": [
    "S39"
   ],
   "note": "Soviet Moon rocket, 4 failed launches 1969 to 1972. 4,500 tf per RussianSpaceWeb; other sources give 45.4 MN. Diameter is the base."
  },
  {
   "name": "Falcon 9",
   "height_m": 70,
   "diameter_m": 3.7,
   "thrust_MN": 7.607,
   "payload_leo_t": 22.8,
   "src": [
    "S38"
   ],
   "note": "Payload expendable."
  },
  {
   "name": "Falcon Heavy",
   "height_m": 70,
   "diameter_m": 12.2,
   "thrust_MN": 22.819,
   "payload_leo_t": 63.8,
   "src": [
    "S38"
   ],
   "note": "12.2 m is overall width; payload expendable."
  },
  {
   "name": "New Glenn",
   "height_m": 98,
   "diameter_m": 7,
   "thrust_MN": 17.1,
   "payload_leo_t": 45,
   "src": [
    "S40"
   ],
   "note": "7x2 configuration; 3.85 Mlbf baseline (BE-4 uprates announced)."
  },
  {
   "name": "Starship V2 (2025)",
   "height_m": 123,
   "diameter_m": 9,
   "thrust_MN": 74.4,
   "payload_leo_t": null,
   "src": [
    "S10"
   ],
   "note": "7,590 tf. SpaceX did not publish a separate V2 payload rating; about 35 t is a press figure."
  },
  {
   "name": "Starship V3",
   "height_m": 124,
   "diameter_m": 9,
   "thrust_MN": 80.8,
   "payload_leo_t": 100,
   "src": [
    "S1"
   ],
   "note": "8,240 tf (18.1 Mlbf); 100+ t fully reusable. About 2.4 times Saturn V liftoff thrust."
  }
 ]
};
