"""Regenerate js/data.js from research/facts.json (validates JSON and flags dashes)."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = ROOT / "research" / "facts.json"
data = json.loads(src.read_text(encoding="utf-8"))

text = json.dumps(data, ensure_ascii=False, indent=1)
bad = [ch for ch in ("—", "–") if ch in text]
if bad:
    text = text.replace("—", ", ").replace("–", "-")
    print("replaced em/en dashes in facts data")

out = ROOT / "js" / "data.js"
out.write_text("/* Generated by tools/build_data.py from research/facts.json. Do not edit by hand. */\n"
               "window.SX_DATA = " + text + ";\n", encoding="utf-8")
print(f"wrote {out} ({len(data.get('facts', {}))} facts, {len(data.get('sources', {}))} sources, "
      f"{len(data.get('timeline', []))} timeline events, {len(data.get('flights', []))} flights)")
missing = [k for k, f in data.get("facts", {}).items() if f.get("v") is None]
if missing:
    print("facts with null values:", ", ".join(missing))
sys.exit(0)
